version: '3.8'

services:
  # Servicio de MySQL
  db:
    image: mysql:8.0
    container_name: tablero_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-tablero_db}
      MYSQL_USER: ${DB_USER:-tablero_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-tablero_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # Servicio del servidor API
  server:
    build: ./server
    container_name: tablero_server
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER:-tablero_user}
      DB_PASSWORD: ${DB_PASSWORD:-tablero_pass}
      DB_NAME: ${DB_NAME:-tablero_db}
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app_network

  # Servicio del cliente React
  client:
    build: ./client
    container_name: tablero_client
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
