version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tablero_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tablero_db
      MYSQL_USER: tablero_user
      MYSQL_PASSWORD: tablero_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tablero_network

  server:
    build: ./server
    container_name: tablero_server
    restart: always
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=tablero_user
      - DB_PASSWORD=tablero_password
      - DB_NAME=tablero_db
      - DB_PORT=3306
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - tablero_network
    command: npm start

  client:
    build: ./client
    container_name: tablero_client
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - tablero_network
    depends_on:
      - server

networks:
  tablero_network:
    driver: bridge

volumes:
  mysql_data:
